POST http://127.0.0.1:3000/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "Alex Júnior",
    "birthDate": "1997-04-29",
    "email": "alexjr.anp@gmail.com",
    "password": "123456789",
    "gender": "Male"

}
###

POST http://127.0.0.1:3000/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "email": "alexjr.anp@gmail.com",
    "password": "123456789",
}
###

GET http://127.0.0.1:3000/api/v1/users HTTP/1.1
###

GET http://127.0.0.1:3000/api/v1/users/875d867f-d966-4372-a30f-883c1f7ff7cd HTTP/1.1
###